# helm/product-service/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.global.namespace | default .Values.namespace }}
data:
  application.yml: |
    server:
      port: 8080
      servlet:
        context-path: /api

    spring:
      application:
        name: product-service
      datasource:
        url: jdbc:h2:mem:productdb
        driver-class-name: org.h2.Driver
        username: sa
        password:
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
          ddl-auto: update
        show-sql: true
      h2:
        console:
          enabled: true
          path: /h2-console

    # Add actuator endpoints for health checks
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics
      endpoint:
        health:
          show-details: always