# helm/product-service/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace | default .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount | default .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ if .Values.global }}{{ .Values.global.registry }}{{ else }}paveldockertest.azurecr.io{{ end }}/{{ .Values.image.repository }}:{{ if .Values.global.imageTag }}{{ .Values.global.imageTag }}{{ else }}{{ .Values.image.tag }}{{ end }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy | default .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          env:
            - name: SPRING_CONFIG_LOCATION
              value: file:/app/config/application.yml
          resources:
            requests:
              cpu: {{ .Values.global.resources.requests.cpu | default .Values.resources.requests.cpu }}
              memory: {{ .Values.global.resources.requests.memory | default .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.global.resources.limits.cpu | default .Values.resources.limits.cpu }}
              memory: {{ .Values.global.resources.limits.memory | default .Values.resources.limits.memory }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Chart.Name }}-config