# helm/product-service/values.yaml
# Default values for product-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
namespace: fex-multiple-services

image:
  repository: product-service
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

probes:
  liveness:
    path: /api/actuator/health
    initialDelaySeconds: 60
    periodSeconds: 15
  readiness:
    path: /api/actuator/health
    initialDelaySeconds: 30
    periodSeconds: 10