# helm/microservices/values.yaml
global:
  namespace: fex-multiple-services
  registry: paveldockertest.azurecr.io
  imageTag: latest
  imagePullPolicy: Always
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

product-service:
  enabled: true
  replicas: 2
  service:
    type: LoadBalancer
    port: 80
    targetPort: 8080

order-service:
  enabled: true
  replicas: 2
  service:
    type: LoadBalancer
    port: 80
    targetPort: 8080
  ingress:
    enabled: true
    path: /order(/|$)(.*)
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
