# Namespace definition
apiVersion: v1
kind: Namespace
metadata:
  name: fex-multiple-services
  labels:
    name: fex-multiple-services
---
# ConfigMap for application properties
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: fex-multiple-services
data:
  application.yml: |
    server:
      port: 8080
      servlet:
        context-path: /api

    spring:
      application:
        name: product-service
      datasource:
        url: jdbc:h2:mem:productdb
        driver-class-name: org.h2.Driver
        username: sa
        password:
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
          ddl-auto: update
        show-sql: true
      h2:
        console:
          enabled: true
          path: /h2-console

    # Add actuator endpoints for health checks
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics
      endpoint:
        health:
          show-details: always
---
# Service definition
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: fex-multiple-services
  labels:
    app: product-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: product-service
---
# Deployment for product-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: fex-multiple-services
  labels:
    app: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: paveldockertest.azurecr.io/product-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          env:
            - name: SPRING_CONFIG_LOCATION
              value: file:/app/config/application.yml
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: config-volume
          configMap:
            name: product-service-config
