name: Build and Push React App to Azure Container Registry

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx with container driver to properly support caching
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          # Use the docker-container driver explicitly
          driver: docker-container
          # Use a specific buildx version
          buildkitd-flags: --debug
          # Make sure all context needed for caching is available
          endpoint: unix:///var/run/docker.sock

      # Verify the builder is using the correct driver
      - name: Verify Buildx Setup
        run: |
          echo "Builder info:"
          docker buildx inspect
          echo "Builder drivers:"
          docker info | grep -i driver

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Then build with all options and push directly
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./fe-service
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.ACR_LOGIN_SERVER }}/react-app:latest
            ${{ secrets.ACR_LOGIN_SERVER }}/react-app:${{ github.sha }}
          # Use registry caching instead of GHA caching
          cache-from: type=registry,ref=${{ secrets.ACR_LOGIN_SERVER }}/react-app:latest
          cache-to: type=inline

      - name: Smoke Test - Verify Image
        run: |
          # Get the image reference
          IMAGE_REF="${{ secrets.ACR_LOGIN_SERVER }}/react-app:latest"
          
          # Pull the image
          docker pull $IMAGE_REF
          
          # Show image details
          echo "Image details:"
          docker inspect $IMAGE_REF
          
          # Run the container with a simple command to verify it starts
          echo "Running smoke test container..."
          CONTAINER_ID=$(docker run -d -p 8080:80 $IMAGE_REF)
          
          # Check if container started successfully
          if [ -z "$CONTAINER_ID" ]; then
            echo "Failed to start container for smoke test"
            exit 1
          fi
          
          # Wait for container to initialize
          sleep 5
          
          # Get logs
          echo "Container logs:"
          docker logs $CONTAINER_ID
          
          # Check if container is running
          CONTAINER_STATUS=$(docker inspect $CONTAINER_ID --format='{{.State.Status}}')
          
          # Clean up container
          docker stop $CONTAINER_ID
          docker rm $CONTAINER_ID
          
          # Check status
          if [ "$CONTAINER_STATUS" != "running" ]; then
            echo "Smoke test failed: Container is not running"
            exit 1
          fi
          
          echo "Smoke test passed: React app container is running"