name: Build and Push to Azure Container Registry

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run:  |       
            cd order-service
            mvn clean package -DskipTests

      # Create and use a new builder that properly supports caching
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          use: true
          driver-opts: |
            image=moby/buildkit:latest
            network=host

      # Explicitly list builders to verify
      - name: List builders
        run: docker buildx ls

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build without push first to test if the image builds correctly
      - name: Test Image Build
        uses: docker/build-push-action@v5
        with:
          context: ./order-service
          push: false
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/order-service:test
          platforms: linux/amd64
          load: true

      # Then build with all options and push
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./order-service
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.ACR_LOGIN_SERVER }}/order-service:latest
            ${{ secrets.ACR_LOGIN_SERVER }}/order-service:${{ github.sha }}
          # Comment out cache options until the builder is confirmed working
          # cache-from: type=gha
          # cache-to: type=gha,mode=max

      - name: Smoke Test - Verify Image Name
        run: |
          # Get the image reference
          IMAGE_REF="${{ secrets.ACR_LOGIN_SERVER }}/order-service:latest"
          
          # Pull the image
          docker pull $IMAGE_REF
          
          # Show image details
          echo "Image details:"
          docker inspect $IMAGE_REF
          
          # Run the container with a simple command to verify it starts
          echo "Running smoke test container..."
          CONTAINER_ID=$(docker run -d $IMAGE_REF sh -c "echo 'Image name test'")
          
          # Check if container started successfully
          if [ -z "$CONTAINER_ID" ]; then
            echo "Failed to start container for smoke test"
            exit 1
          fi
          
          # Get logs
          echo "Container logs:"
          docker logs $CONTAINER_ID
          
          # Wait for container to complete
          docker wait $CONTAINER_ID
          
          # Get exit code
          EXIT_CODE=$(docker inspect $CONTAINER_ID --format='{{.State.ExitCode}}')
          
          # Clean up container
          docker rm $CONTAINER_ID
          
          # Check exit code
          if [ "$EXIT_CODE" -ne 0 ]; then
            echo "Smoke test failed with exit code $EXIT_CODE"
            exit $EXIT_CODE
          fi
          
          echo "Smoke test passed: Image name verification successful"